version: '3.8'

# Override file for Cloudflare Tunnel mode
# Use with: docker-compose -f docker-compose.yml -f docker-compose.cloudflare.yml up -d

services:
  # Override nginx to use HTTP only and share VPN network
  nginx:
    network_mode: "service:vpn"  # Both nginx and cloudflared in VPN namespace
    volumes:
      - ./nginx-cloudflare.conf:/etc/nginx/templates/nginx.conf.template:ro
      - certbot-data:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro

  # Remove certbot - not needed with Cloudflare
  certbot:
    entrypoint: /bin/sh -c "echo 'Certbot disabled in Cloudflare mode' && sleep infinity"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: rtve-cloudflared
    network_mode: "service:vpn"  # Share VPN namespace with nginx
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared:ro
    depends_on:
      - vpn
      - nginx
    restart: unless-stopped
